# Generated by Django 3.1.6 on 2022-07-05 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=5)),
                ('specialite', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=5)),
                ('Age', models.IntegerField()),
                ('groupe_sangin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Echo abdominal', 'Echo abdominal'), ('Echo Pelvienne', 'Echo Pelvienne'), ('Echo Arbre urinaire', 'Echo Arbre urinaire'), ('Echo Obstétricale', 'Echo Obstétricale'), ('Echo Obstétrical 3D/4D', 'Echo Obstétrical 3D/4D'), ('Echo mamaire(sein)', 'Echo mamaire(sein)'), ('Echo parties moles', 'Echo parties moles'), ('Echo bourses(Testicules)', 'Echo bourses (Testicules)'), ('Echo épaule-Genoux', 'Echo épaule-Génoux'), ('Echo Doppler', 'Echo Doppler'), ('TSA', 'TSA'), ('Membre inférieur', 'Membre inférieur'), ('Membres inférieur', 'Membres inférieur'), ('Bourses', 'Bourses')], max_length=50)),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_srv', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_res', models.DateField(default=django.utils.timezone.now)),
                ('observation', models.TextField()),
                ('nom_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prima_app.medecins')),
                ('nom_pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prima_app.patients')),
                ('nom_serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prima_app.services')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rv', models.DateTimeField()),
                ('description', models.TextField()),
                ('staut', models.BooleanField(default=False)),
                ('nom_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prima_app.medecins')),
                ('nom_pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prima_app.patients')),
            ],
        ),
    ]
