# Generated by Django 3.1.6 on 2022-07-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prima_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medecins',
            new_name='Medecin',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
        migrations.RenameModel(
            old_name='Resultats',
            new_name='Resultat',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
