# Generated by Django 3.1.6 on 2022-08-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prima_app', '0002_auto_20220707_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='data_rv',
            new_name='date_rv',
        ),
        migrations.RenameField(
            model_name='rendezvous',
            old_name='staut',
            new_name='status',
        ),
    ]
