# Generated by Django 3.1.6 on 2022-08-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prima_app', '0003_auto_20220801_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='num_res',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
